#! /bin/bash
#
# run the network-users.yml playbook in check mode for daily report
# NB: currently only for ios. eg:  --limit 's-*:t-*:r-*'
#
export ANSIBLE_CALLBACKS_ENABLED=''
export ANSIBLE_STDOUT_CALLBACK="json"
export DEVINFORC="/usr/local/ns/etc/devinforc"
#
cat << EOF > /home/net/cms/..callhome_audit.txt
# This file is generated by the ansible playbook /home/net/ns-ansible-uwmadison/ansible/network-callhome.yml
# run in check mode.  network-callhome.yml ensures IOS-XE devices with Smart Licencing are configured to
# use the HTTP Proxy to call-home on the cms_service_ipv4 for cms.net.wisc.edu / cms.lab.net.wisc.edu
# 
# The following lines are the "change" items it reported with the playbook remediation.
#
EOF
#
exec /home/net/ns-ansible-uwmadison/ansible/netbox-playbook.sh /home/net/ns-ansible-uwmadison/ansible/network-callhome.yml --limit 's-*:t-*:r-*' --check 2>/home/net/cms/..callhome_audit_err.txt | /bin/jq -r '.plays[].tasks[].hosts | to_entries | .[] | select(.value.changed and .value.results) | [.key, (.value.results[] | select(.commands) .commands | join("; ") | sub("\n"; "") ) ] | @csv' | /bin/sed -re 's/(password|secret) ?([0-9])? (\S+) ([^\"]+)"/\1 \2 XXXXXXXXX \4"/g' >> /home/net/cms/..callhome_audit.txt
