---
all:
  hosts:
    localhost:
      ansible_become: false
      ansible_pipelining: false
  vars:
    # ansible_python_interpreter: auto_silent
    # ansible_python_interpreter: /usr/bin/python3
    ansible_network_import_modules: true
    ansible_host_key_auto_add: true
    ansible_host_key_checking: false
    # netbox_devinfo: "{{ lookup('pipe','/usr/local/ns/bin/devinfo -j netbox-' + inventory_hostname) | from_json }}"
    # netbox_api: "{{ netbox_devinfo.connection_method }}://{{ netbox_devinfo.attributes.host }}:{{ netbox_devinfo.attributes.port }}/"
    # netbox_token: "{{ netbox_devinfo.password }}"
    netbox_api: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    cms_service_ipv4: "146.151.144.19"
    cms_service_ipv6: "2607:f388:2:2000::1037"
    traps_service_ipv4: "146.151.144.18"
    devinfo: "{{ lookup('pipe','/usr/local/ns/bin/devinfo -j ' + inventory_hostname) | from_json }}"
    net_devinfo: "{{ lookup('pipe','/usr/local/ns/bin/devinfo -j default') | from_json }}"
    snmp_devinfo: "{{ lookup('pipe','/usr/local/ns/bin/devinfo -j snmp-' + inventory_hostname) | from_json }}"
    emergency_user: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j emergency') | from_json }}"
    old_emergency_user: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j emergency-old') | from_json }}"
    enable_secret: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j enable') | from_json }}"
    old_enable_secret: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j enable-old') | from_json }}"
    housing_enable_secret: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j enable-housing') | from_json }}"
    radius_secret: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j radius') | from_json }}"
    netbox_devinfo: "{{ lookup('pipe','/usr/local/ns/bin/devinfo -j netbox-prod') | from_json }}"
    # Netflow collection
    frr_devinfo: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j frr-' + inventory_hostname ) | from_json}}"
    junos_rest_http_port: 3000
    junos_rest_https_port: 3443
    junos_rest_https_cert: rest-tls-key
    junos_groups_dir: /usr/local/uwsysnet-iptrack/etc/configdata/juniper/juniper-groups
    # junos_groups_dir: /network/juniper-groups
    junos_groups:
      - sync_bfd-ospf-mx10003
      - sync_chassis-mx10003
      - sync_class-of-service
      - sync_class-of-service-mx10003
      - sync_communities
      - sync_ddos-protection-mx10003-20.4R3-S5.4
      - sync_ethernet-standards
      - sync_firewall-policers
      - sync_forwarding-options-sampling
      - sync_fw-inet6-deny
      - sync_fw-inet6-drop-protocols
      - sync_fw-inet6-established-mgmt
      - sync_fw-inet6-protect-re
      - sync_fw-inet6-remote-access
      - sync_fw-inet-accept
      - sync_fw-inet-count-accept-cos-traffic
      - sync_fw-inet-count-application-traffic
      - sync_fw-inet-count-traffic
      - sync_fw-inet-deny
      - sync_fw-inet-drop-fragments
      - sync_fw-inet-established-mgmt
      - sync_fw-inet-protect-re
      - sync_fw-inet-remote-access
      - sync_fw-mpls-count-accept-traffic
      - sync_fxp0-lab
      - sync_interfaces-ndp-cache-protection
      - sync_lacp-standards
      - sync_maintenance-policy
      - sync_prefix-list-apply-path
      - sync_protocols-bgp
      - sync_protocols-bgp-iBGP-reflector-client-v4
      - sync_protocols-bgp-iBGP-reflector-client-v6
      - sync_protocols-bgp-iBGP-reflector-v4-lab-servers
      - sync_protocols-bgp-iBGP-reflector-v6-lab-servers
      - sync_protocols-bgp-iBGP-v4
      - sync_protocols-bgp-iBGP-v6
      - sync_protocols-igmp
      - sync_protocols-ldp
      - sync_protocols-ldp-auth
      - sync_protocols-lldp
      - sync_protocols-mpls
      - sync_protocols-ospf3-mx10003
      - sync_protocols-ospf-mx10003
      - sync_protocols-pim
      - sync_RE-redundancy
      - sync_routing-options-flowspec
      - sync_routing-options-multicast
      - sync_routing-options-mx10003
      # - sync_security
      - sync_services
      - sync_snmp
      - sync_system-login
      - sync_system-mx10003
    netflow_exporters:
      - name: flows.net.wisc.edu
        ip: 146.151.144.16
        port: 4007
        version: 9
      - name: flows2.net.wisc.edu
        ip: 146.151.144.53
        port: 4007
        version: 9
  children:
    qa:
      vars:
        site_environment: "qa"
        syslog_doit_ns:
          - "146.151.144.103" # netlog3-lab
          - "146.151.144.104" # netlog4-lab
        syslog_doit_ns_ipv6:
          - "2607:f388:2:2000::1068" # netlog3-lab
          - "2607:f388:2:2000::1069" # netlog4-lab
        syslog_doit_ns_oob:
          - "10.151.90.190"
          - "10.151.90.191"
        flows_primary_ip4: "146.151.144.103"
        flows_primary_ip6: ""
        flows_secondary_ip4: "146.151.144.104"
        flows_secondary_ip6: ""
    prod:
      vars:
        site_environment: "prod"
        syslog_doit_ns:
          - "146.151.144.13" # syslog-vip
          - "146.151.144.54" # syslog2-vip
        syslog_doit_ns_ipv6:
          - "2607:f388:2:2000::100c" # syslog-vip
          - "2607:f388:2:2000::1014" # syslog2-vip
        syslog_doit_ns_oob:
          - "10.151.90.134" # incorrect syslog-oob-vip
          - "10.151.90.135" # incorrect syslog2-oob-vip
          - "10.151.90.190" # actual syslog-oob-vip
          - "10.151.90.191" # actual syslog2-oob-vip
        flows_service_ipv4:
          - "146.151.144.16" # flows-vip
          - "146.151.144.53" # flows2-vip
        flows_service_ipv6:
          - "2607:f388:2:2000::1004" # flows-vip
          - "2607:f388:2:2000::1013" # flows2-vip
        flows_service_ipv46: "{{ flows_service_ipv4 + flows_service_ipv6 }}"
        cms_service_ipv4: "146.151.144.19"
        cms_service_ipv6: "2607:f388:2:2000::1037"

    vlan_area_lab:
      vars:
        cms_service_ipv4: "146.151.144.26"
        cms_service_ipv6: "2607:f388:2:2000::1038"
        netflow_exporters:
          - name: flows.net.wisc.edu
            ip: 146.151.144.16
            port: 4007
            version: 9
          # - name: flows2.net.wisc.edu
          #   ip: 146.151.144.53
          #   port: 4007
          #   version: 9
          - name: onmscore1-lab.doit.wisc.edu
            ip: 146.151.144.81
            port: 4729
            version: 9
          # - name: entpoll2-lab.doit.wisc.edu
          #   ip: 146.151.144.21
          #   port: 9996
          #   version: 9
          - name: flows.lab.net.wisc.edu
            ip: 146.151.144.103
            port: 4007
            version: 9
    ios_12:
      children:
        platforms_ios_12_027:
        platforms_ios_12_218sxf13:
        platforms_ios_12_233sxi8:
        platforms_ios_12_244se2:
        platforms_ios_12_255se12:
        platforms_ios_12_255se3:
        platforms_ios_12_425d:
      vars:
        ios_enable_line: "enable secret 5 {{ enable_secret.attributes.type5hash }}"
        ios_users:
          - name: emerg
            hashed_password:
              type: 5
              value: "{{ emergency_user.attributes.type5hash  }}"
            privilege: 15
      #       - name: "net"
      #         nopassword: True
      #         sshkey: "{{ lookup('file', '/home/net/.ssh/id_rsa.pub') }}"
      #         privilege: 15
      #         state: present
    ios_15:
      children:
        platforms_ios_15_24e10:
        platforms_ios_15_27e5:
        platforms_ios_15_420141205102348_arrathin_v1522t_mprmt_116:
        platforms_ios_15_93m4:
        platforms_ios_15_93m5:
        platforms_ios_15_93m7:
        platforms_iosxe_03_05_02_e:
        platforms_iosxe_03_06_01_e:
        platforms_iosxe_03_06_03_e:
        platforms_iosxe_03_06_06_e:
        platforms_iosxe_03_07_01_e:
        platforms_iosxe_03_07_05e:
        platforms_iosxe_03_08_05a_e:
        platforms_iosxe_03_08_05_e:
        platforms_iosxe-03_16_04b_s_155_3_s4b_ext:
        platforms_iosxe_16_09_04:
        platforms_iosxe_16_8_1:
        platforms_iosxe_bengaluru_17_06_03:
        platforms_iosxe_bengaluru_17_06_05:
        platforms_iosxe_17_6_5:
        platforms_iosxe_everest_16_6_5:
        platforms_iosxe_everest_16_6_8:
        platforms_iosxe_gibraltar_16_12_05b:
        platforms_iosxe_dublin_17_12_02: # ?for s-hotspare-b360-10-hotspare version 17.12 or should this be in netbox
        platforms_iosxe_dublin_17_12_03:
        platforms_iosxe_cupertino_17_09_03:
        # ios_15_regulatedsecurity:
        ios_15_highsecurity:
          children:
            device_roles_fisma:
            device_roles_restr:
          vars:
            # FIXME: I know this is wrong, need to add fisma and restr hashes to devinforc
            #        and normalize hashes on restr devices.  if they need to be different
            #        then we need separate vars for each
            ios_enable_line: "enable secret 8 {{ enable_secret.attributes.type8hash }}"
            ios_users:
              - name: emerg
                hashed_password:
                  type: 8
                  value: "{{ emergency_user.attributes.type8hash  }}"
                privilege: 15
              - name: net
                hashed_password:
                  type: 8
                  # FIXME: need to verify default cred for fisma/restr hosts includes hashes in devinforc
                  value: "{{ devinfo.attributes.type8hash }}"
                privilege: 5
              # List of admins with fisma, restr admin privileges
              - name: bbadger
                privilege: 15
      vars:
        ios_enable_line: "enable secret 8 {{ enable_secret.attributes.type8hash }}"
        ios_users:
          - name: emerg
            hashed_password:
              type: 8
              value: "{{ emergency_user.attributes.type8hash  }}"
            privilege: 15
    #       - name: "net"
    #         nopassword: True
    #         sshkey: "{{ lookup('file', '/home/net/.ssh/id_rsa.pub') }}"
    #         privilege: 15
    #         state: present
    ios_17:
      children:
        platforms_iosxe_bengaluru_17_06_03:
        platforms_iosxe_bengaluru_17_06_05:
        platforms_iosxe_17_6_5:
        platforms_iosxe_cupertino_17_09_03:
        platforms_iosxe_dublin_17_12_02: # ?for s-hotspare-b360-10-hotspare version 17.12 or should this be in netbox
        platforms_iosxe_dublin_17_12_03:
    # ios_15_ansible:
    #   hosts:
    #     s-cssclabqa-b217-10-access:
    #   vars:
    #     ios_enable_line: "enable secret 8 {{ enable_secret.attributes.type8hash }}"
    #     ios_users:
    #       - name: emerg
    #         hashed_password:
    #           type: 8
    #           value: "{{ emergency_user.attributes.type8hash  }}"
    #         privilege: 15
    #       - name: "ansible"
    #         nopassword: True
    #         sshkey: "{{ lookup('file', '/home/net/.ssh/id_rsa.pub') }}"
    #         privilege: 15
    #         state: present
    nxos:
      children:
        nxos_9:
          children:
            platforms_nxos_9_37a:
          vars:
        nxos_7:
          children:
            platforms_nxos_7_30n11:
            platforms_nxos_7_35d11:
            platforms_nxos_7_37n11b:
            platforms_nxos_7_38n11:
          vars:
        nxos_8:
          children:
            platforms_nxos_8_43:
          vars:
        platforms_nxos:
      vars:
        nxos_users:
          - name: emerg
            hashed_password: "{{ emergency_user.attributes.type5hash }}"
          - name: admin
            hashed_password: "{{ emergency_user.attributes.type5hash }}"

    panos:
      children:
        panos_8:
          children:
            platforms_panos_8_1_13:
          vars:
        panos_9:
          children:
            platforms_panos_9_0_12:
          vars:
        platforms_panos:
      vars:
        panos_users:
          - name: admin
            hashed_password: "{{ emergency_user.attributes.type256hash }}"
          - name: emerg
            hashed_password: "{{ emergency_user.attributes.type256hash }}"
