---
- name: IOS VTY
  hosts: s-*:r-*:t-*:VG-*
  gather_facts: false
  connection: ansible.netcommon.network_cli
  become:  "{{ 'False' if ansible_check_mode else 'True' }}"
  become_method: ansible.netcommon.enable
  serial:
    - 50
    - 100
    # - 500
  max_fail_percentage: 10
  vars:
    ansible_network_import_modules: true
    ansible_host_key_auto_add: true
    # ansible_private_key_file: "/home/net/.ssh/id_rsa.pub"
    # ansible_net_ssh_keyfile: "/home/net/.ssh/id_rsa.pub"
    ansible_network_os: "cisco.ios.ios"
    # ansible_network_cli_ssh_type: libssh
    ansible_network_cli_ssh_type: paramiko
    ansible_command_timeout: 300
    ansible_connect_timeout: 300
    net_user: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j ' + inventory_hostname) | from_json }}"
    # net_user: "{{ lookup('pipe', '/usr/local/ns/bin/devinfo -j emergency-' + inventory_hostname) | from_json }}"
    ansible_user: "{{ net_user.username }}"
    ansible_password: "{{ net_user.password }}"
    ansible_become_password: "{{ net_user.enable_password }}"
    netbox_devinfo: "{{ lookup('pipe','/usr/local/ns/bin/devinfo -j netbox-prod') | from_json }}"
    netbox_api: "{{ netbox_devinfo.connection_method }}://{{ netbox_devinfo.attributes.host }}:{{ netbox_devinfo.attributes.port }}/"
    netbox_token: "{{ netbox_devinfo.password }}"
    platform_family: "{{ platforms[0].split('-')[0] }}"
    device_family: "{{ device_types[0] | regex_search('^(ap\\d\\d\\d|ws-c\\d+|c9\\d+)', '\\1') | first }}"
    # netdevice_inventory: "{{ query('netbox.netbox.nb_lookup', 'devices', api_filter='status=active has_primary_ip=True', api_endpoint=netbox_api, token=netbox_token) }}"
    # netbox_vlans: "{{ query('netbox.netbox.nb_lookup', 'vlans', api_endpoint=netbox_api, token=netbox_token) | items2dict(key_name='key', value_name='value') }}"
    # ansible_net_config: "{{ lookup('pipe', '/usr/bin/co -q -p /home/net/cms/' + inventory_hostname + '.conf') }}"
    # ansible_net_config: "{{ lookup('file', '/home/net/cms/' + inventory_hostname + '.conf') }}"
    cisco_vty_config:

  tasks:
    - name: Set ansible_net_config
      block:
        - name: Get Config from NetCMS
          set_fact:
            ansible_net_config: "{{ lookup('pipe', '/usr/bin/co -q -p /home/net/cms/' + inventory_hostname + '.conf') }}"
            netcms_enabled: true
        - name: Get Minimal Facts
          cisco.ios.ios_facts:
            gather_subset: "min"
      rescue:
        - name: Disable NetCMS Check-in
          set_fact:
            netcms_enabled: false
        - name: Get Facts from live device
          cisco.ios.ios_facts:
            gather_subset: "config"
        - name: Show Facts from device (hostname, model, image, version)
          debug:
            msg: "DEBUG {{ inventory_hostname }} {{ ansible_net_hostname }} {{ ansible_net_model }} {{ ansible_net_image }} {{ ansible_net_version }}"
    - name: Configure Console stanza
      cisco.ios.ios_config:
        running_config: "{{ ansible_net_config }}"
        parents: "line con 0"
        lines:
          - "exec-timeout 60 0"
          - "logging synchronous"
          - "stopbits 1"
        save_when: never
      notify: "copy running-config startup-config"
    - name: Configure VTY stanza lines 0-4
      when: "'line vty 0 4' in ansible_net_config"
      cisco.ios.ios_config:
        running_config: "{{ ansible_net_config }}"
        parents: "line vty 0 4"
        lines:
          - "access-class G-A-AdminAccess in"
          - "exec-timeout 60 0"
          - "ipv6 access-class G-A-v6AdminAccess in"
          - "logging synchronous"
          - "transport input telnet ssh"
        save_when: never
      notify: "copy running-config startup-config"
    - name: Configure VTY stanza lines 5-15
      when: "'line vty 5 15' in ansible_net_config"
      cisco.ios.ios_config:
        running_config: "{{ ansible_net_config }}"
        parents: "line vty 5 15"
        lines:
          - "access-class G-A-AdminAccess in"
          - "exec-timeout 60 0"
          - "ipv6 access-class G-A-v6AdminAccess in"
          - "logging synchronous"
          - "transport input telnet ssh"
        save_when: never
      notify: "copy running-config startup-config"
    - name: Configure VTY stanza lines 16-31
      when: "'line vty 16 31' in ansible_net_config"
      cisco.ios.ios_config:
        running_config: "{{ ansible_net_config }}"
        parents: "line vty 16 31"
        lines:
          - "access-class G-A-AdminAccess in"
          - "exec-timeout 60 0"
          - "ipv6 access-class G-A-v6AdminAccess in"
          - "logging synchronous"
          - "transport input telnet ssh"
        save_when: never
      notify: "copy running-config startup-config"
    - name: Configure VTY stanza lines 5-31
      when: "'line vty 5 31' in ansible_net_config"
      cisco.ios.ios_config:
        running_config: "{{ ansible_net_config }}"
        parents: "line vty 5 31"
        lines:
          - "access-class G-A-AdminAccess in"
          - "exec-timeout 60 0"
          - "ipv6 access-class G-A-v6AdminAccess in"
          - "logging synchronous"
          - "transport input telnet ssh"
        save_when: never
      notify: "copy running-config startup-config"
  handlers:
    - name: copy running-config startup-config
      when: "not ansible_check_mode"
      cisco.ios.ios_command:
        commands:
          - "write memory"
        wait_for: "result[0] contains '[OK]'"
      ignore_errors: "{{ ansible_check_mode }}"
    - name: NetCMS Check-in
      when: "not ansible_check_mode and netcms_enabled"
      listen: "copy running-config startup-config"
      command:
        # chdir: "/home/net/cms/"
        argv:
          - "/usr/bin/make"
          - "-f"
          - "/home/net/cms/Makefile"
          - "logmsg=ansible configuration {{ ansible_play_name }} by {{ lookup('env', 'LOGNAME') }}"
          - "/home/net/cms/{{ inventory_hostname }}.update"
      delegate_to: localhost


