---
roles:
  - name: mtinberg.netbox
    src: https://github.com/mtinberg/ansible-role-netbox.git
    version: old-netbox-3.0
  - name: lae.netbox
    src: https://github.com/lae/ansible-role-netbox.git
    version: "v1.0.6"
  # https://github.com/geerlingguy/ansible-role-postgresql
  - name: geerlingguy.postgresql
    version: 3.5.0
  - src: https://github.com/scylladb/scylla-ansible-roles
    # name: ansible-scylla-node
collections:
  # https://galaxy.ansible.com/ui/repo/published/netbox/netbox/docs/
  - name: netbox.netbox
    # FIXME: Latest requires Ansible >+ 2.10 and Python >= 3.8,
    #        not Ansible 2.9 on Python 3.6 in EL7
    # version: 3.17.0 Latest
    # version: 3.5 requires Ansible >= 2.10, python >= 3.8 and pynetbox >= 5.0.4 (supports pynetbox 6.4.0 for netbox 3.1+ features)
    # version: 3.2.0 requires python >= 3.6 and pynetbox >= 5.0.4, packaging (on Ansible 2.9)
    #          pynetbox >= 5.0.4 requires python >= 3.8
    version: 3.17.0
  # https://galaxy.ansible.com/ui/repo/published/ansible/netcommon/docs/
  - name: ansible.netcommon
    version: 5.3.0
  # https://galaxy.ansible.com/ui/repo/published/ansible/utils/docs/
  - name: ansible.utils
    version: 2.11.0
  # https://galaxy.ansible.com/ui/repo/published/ansible/posix/docs/
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
  - name: community.postgresql
  - name: community.mysql
  # https://galaxy.ansible.com/ui/repo/published/community/crypto/docs/
  - name: community.crypto
    version: 2.15.1
  # https://galaxy.ansible.com/ui/repo/published/arubanetworks/aos_switch/docs/
  # - name: arubanetworks.aos_switch
  #   version: 1.7.0
  # https://galaxy.ansible.com/ui/repo/published/cisco/ios/docs/
  - name: cisco.ios
    version: 5.3.0
  # https://galaxy.ansible.com/ui/repo/published/cisco/nxos/docs/
  - name: cisco.nxos
    version: 5.3.0
  # https://galaxy.ansible.com/ui/repo/published/junipernetworks/junos/docs/
  - name: junipernetworks.junos
    version: 5.3.0
  # https://galaxy.ansible.com/ui/repo/published/paloaltonetworks/panos/docs/
  - name: paloaltonetworks.panos
    version: 2.17.4
  # https://galaxy.ansible.com/ui/repo/published/citrix/adc/docs/
  # - name: citrix.adc
  #   version: 1.2.0
  # https://galaxy.ansible.com/ui/repo/published/infoblox/nios_modules/docs/
  # - name: infoblox.nios_modules
  # https://galaxy.ansible.com/ui/repo/published/grafana/grafana/docs/
  # - name: grafana.grafana
  # https://galaxy.ansible.com/ui/repo/published/prometheus/prometheus/docs/
  # - name: prometheus.prometheus
  # https://galaxy.ansible.com/ui/repo/published/frr/frr/docs/
  # - name: frr.frr
  # - name: containers.podman
  # https://galaxy.ansible.com/ui/repo/published/community/hashi_vault/docs/
  # - name: community.hashi_vault
  # https://galaxy.ansible.com/ui/repo/published/cyberark/conjur/docs/
  # - name: cyberark.conjur
  # https://galaxy.ansible.com/ui/repo/published/community/mysql/docs/
  # - name: community.mysql
  # https://galaxy.ansible.com/ui/repo/published/community/postgresql/docs/
  # - name: community.postgresql
  # https://galaxy.ansible.com/ui/repo/published/community/general/docs/
  # - name: community.general
  #   version: 7.5.0
  # https://galaxy.ansible.com/ui/repo/published/community/elastic/docs/
  # - name: community.elastic
  #   version: 1.1.0
