#! /bin/bash
#
# run the network-users.yml playbook in check mode for daily report
# NB: currently only for ios. eg:  --limit 's-*:t-*:r-*'
#
export ANSIBLE_CALLBACKS_ENABLED=''
export ANSIBLE_STDOUT_CALLBACK="json"
export DEVINFORC="/usr/local/ns/etc/devinforc"
#
cat << EOF > /home/net/cms/..user_audit.txt
# This file is generated by the ansible playbook /home/net/ns-ansible-uwmadison/ansible/network-users.yml
# run in check mode.  The following lines are the "change" items it reported with the playbook remediation.
# For VDC devices, you may see a change in role when the checked in config is correct.  This indicates that
# a device is not tagged in netbox as mgmt_VDC as it should be.
#
EOF
#
exec /home/net/ns-ansible-uwmadison/ansible/netbox-playbook.sh /home/net/ns-ansible-uwmadison/ansible/network-users.yml --limit 's-*:t-*:r-*:rn-*:sn-*' --check 2>/home/net/cms/..user_audit_err.txt | /bin/jq -r '.plays[].tasks[].hosts | to_entries | .[] | select(.value.changed and .value.results) | [.key, (.value.results[] | select(.commands) .commands | join("; ") | sub("\n"; "") ) ] | @csv' | /bin/sed -re 's/(password|secret) ?([0-9])? (\S+) ([^\"]+)"/\1 XXXXXXXXX"/g' >> /home/net/cms/..user_audit.txt
